#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

if [ -z "${TERMUX_VERSION:-}" ] && [ ! -d "/data/data/com.termux/files/usr" ]; then
  printf '%s\n' 'This installer must be run from Termux.' >&2
  exit 1
fi

INSTALL_ROOT="${MORDECAI_INSTALL_ROOT:-$HOME/mordecai}"
BACKEND_DIR="${INSTALL_ROOT}/backend"
ENV_DIR="${INSTALL_ROOT}/env"
DATA_DIR="${INSTALL_ROOT}/data"
STATE_DIR="${DATA_DIR}/state"
LOG_DIR="${DATA_DIR}/logs"
CACHE_DIR="${DATA_DIR}/cache"
MODELS_DIR="${DATA_DIR}/models"
SCRIPT_DIR="${INSTALL_ROOT}/scripts"
ENV_FILE="${INSTALL_ROOT}/.env"
REPO_URL="${MORDECAI_REPO_URL:-https://github.com/smokydastona/Mordecai-AI-Android.git}"
PROOT_DISTRO="${MORDECAI_PROOT_DISTRO:-ubuntu-24.04}"
TERMUX_PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"
TOOLS_DIR="${INSTALL_ROOT}/tools"
ROOTFS_CACHE_DIR="${CACHE_DIR}/rootfs"
UBUNTU_24_04_ALIAS="ubuntu-24.04"
UBUNTU_24_04_CODE_NAME="noble"
UBUNTU_24_04_RELEASE="${MORDECAI_UBUNTU_24_04_RELEASE:-20260323}"
UBUNTU_24_04_BASE_URL="${MORDECAI_UBUNTU_24_04_BASE_URL:-https://cloud-images.ubuntu.com/${UBUNTU_24_04_CODE_NAME}/${UBUNTU_24_04_RELEASE}}"
INSTALL_DEFAULT_MODELS="${MORDECAI_INSTALL_DEFAULT_MODELS:-true}"
INSTALL_LOCAL_MODEL_BINARIES="${MORDECAI_INSTALL_LOCAL_MODEL_BINARIES:-true}"
INSTALL_SHELL_APK="${MORDECAI_INSTALL_SHELL_APK:-true}"
INSTALL_DEBUG_TOOLKIT="${MORDECAI_INSTALL_DEBUG_TOOLKIT:-false}"
FORCE_REINSTALL="${MORDECAI_FORCE_REINSTALL:-false}"
APK_RELEASE_TAG="${MORDECAI_APK_RELEASE_TAG:-android-shell-latest}"
APK_ASSET_NAME="${MORDECAI_APK_ASSET_NAME:-android-shell-debug.apk}"
APK_DOWNLOAD_URL="${MORDECAI_APK_DOWNLOAD_URL:-https://github.com/smokydastona/Mordecai-AI-Android/releases/download/${APK_RELEASE_TAG}/${APK_ASSET_NAME}}"
APK_PACKAGE_NAME="${MORDECAI_APK_PACKAGE_NAME:-ai.mordecai.shell}"
TORCH_CPU_INDEX_URL="${MORDECAI_TORCH_CPU_INDEX_URL:-https://download.pytorch.org/whl/cpu}"
APK_DOWNLOAD_PATH="${CACHE_DIR}/${APK_ASSET_NAME}"
TOOLS_BIN_DIR="${TOOLS_DIR}/bin"
LLAMA_CPP_DIR="${TOOLS_DIR}/llama.cpp"
LLAMA_CPP_BUILD_DIR="${LLAMA_CPP_DIR}/build"

run_in_distro() {
  local command="$1"
  proot-distro login "${PROOT_DISTRO}" --shared-tmp -- /bin/bash -lc "${command}"
}

proot_plugin_file() {
  local base_path="${TERMUX_PREFIX}/etc/proot-distro/${PROOT_DISTRO}"

  if [ -f "${base_path}.sh" ]; then
    printf '%s\n' "${base_path}.sh"
    return 0
  fi

  if [ -f "${base_path}.override.sh" ]; then
    printf '%s\n' "${base_path}.override.sh"
    return 0
  fi

  return 1
}

ubuntu_base_arch() {
  case "$1" in
    aarch64)
      printf '%s\n' 'arm64'
      ;;
    arm)
      printf '%s\n' 'armhf'
      ;;
    i686)
      printf '%s\n' 'i386'
      ;;
    x86_64)
      printf '%s\n' 'amd64'
      ;;
    *)
      return 1
      ;;
  esac
}

ensure_pinned_distro_plugin() {
  local plugin_path

  if [ "${PROOT_DISTRO}" != "${UBUNTU_24_04_ALIAS}" ]; then
    return
  fi

  plugin_path="${TERMUX_PREFIX}/etc/proot-distro/${UBUNTU_24_04_ALIAS}.override.sh"
  mkdir -p "${TERMUX_PREFIX}/etc/proot-distro"
  cat > "${plugin_path}" <<EOF
# Generated by Mordecai Phase 1 installer.
# This plug-in pins Ubuntu 24.04 LTS instead of following the moving upstream 'ubuntu' alias.
DISTRO_NAME="Ubuntu (24.04 LTS)"
DISTRO_COMMENT="Pinned Ubuntu Cloud Image ${UBUNTU_24_04_CODE_NAME}-${UBUNTU_24_04_RELEASE} profile managed by Mordecai."
TARBALL_STRIP_OPT=0

TARBALL_URL['aarch64']="${UBUNTU_24_04_BASE_URL}/${UBUNTU_24_04_CODE_NAME}-server-cloudimg-arm64-root.tar.xz"
TARBALL_SHA256['aarch64']="3c8f36e427583571cb5536b339355b9d9b60c233eb7aed5e51c41b3ceba5accf"
TARBALL_URL['arm']="${UBUNTU_24_04_BASE_URL}/${UBUNTU_24_04_CODE_NAME}-server-cloudimg-armhf-root.tar.xz"
TARBALL_SHA256['arm']="f605e285923f5a8eb66daf0ffef1315c08792bbfccfaded6311b988ee8d547c8"
EOF
}

termux_arch() {
  case "$(uname -m)" in
    aarch64|arm64)
      printf '%s\n' 'aarch64'
      ;;
    arm|armv7l|armv8l)
      printf '%s\n' 'arm'
      ;;
    i686|i386|x86)
      printf '%s\n' 'i686'
      ;;
    x86_64|amd64)
      printf '%s\n' 'x86_64'
      ;;
    riscv64)
      printf '%s\n' 'riscv64'
      ;;
    *)
      return 1
      ;;
  esac
}

plugin_tarball_field() {
  local plugin_file
  local distro_arch="$1"
  local field_name="$2"

  plugin_file="$(proot_plugin_file || true)"
  if [ -z "${plugin_file}" ]; then
    return 1
  fi

  awk -F'"' -v arch="${distro_arch}" -v field_name="${field_name}" '$0 ~ (field_name "\\[\\x27" arch "\\x27\\]=") { print $2; exit }' "${plugin_file}"
}

download_rootfs_archive() {
  local distro_arch
  local source_url
  local expected_sha256
  local tarball_name
  local archive_path
  local actual_sha256

  distro_arch="$(termux_arch)" || return 1
  source_url="$(plugin_tarball_field "${distro_arch}" 'TARBALL_URL')"
  expected_sha256="$(plugin_tarball_field "${distro_arch}" 'TARBALL_SHA256')"

  if [ -z "${source_url}" ]; then
    printf '%s\n' "Unable to read the ${PROOT_DISTRO} rootfs URL from ${TERMUX_PREFIX}/etc/proot-distro/${PROOT_DISTRO}.sh." >&2
    return 1
  fi

  tarball_name="${source_url##*/}"
  archive_path="${ROOTFS_CACHE_DIR}/${tarball_name}"
  mkdir -p "${ROOTFS_CACHE_DIR}"

  if [ ! -f "${archive_path}" ]; then
    printf 'Downloading %s rootfs archive with curl --http1.1...\n' "${PROOT_DISTRO}"
    "${TERMUX_PREFIX}/bin/curl" --http1.1 --fail --retry 5 --retry-connrefused --retry-delay 5 --location \
      --output "${archive_path}.tmp" "${source_url}"
    mv -f "${archive_path}.tmp" "${archive_path}"
  fi

  if [ -n "${expected_sha256}" ]; then
    actual_sha256="$(sha256sum "${archive_path}" | awk '{ print $1 }')"
    if [ "${actual_sha256}" != "${expected_sha256}" ]; then
      rm -f "${archive_path}"
      printf '%s\n' "Downloaded ${PROOT_DISTRO} rootfs checksum did not match the plugin SHA-256; removed the cached archive." >&2
      return 1
    fi
  fi

  printf 'file://%s\n' "${archive_path}"
}

ensure_proot_distro() {
  local fallback_url

  if proot-distro login "${PROOT_DISTRO}" --shared-tmp -- /usr/bin/env true >/dev/null 2>&1; then
    return
  fi

  printf 'Installing proot distro: %s\n' "${PROOT_DISTRO}"
  if proot-distro install "${PROOT_DISTRO}"; then
    return
  fi

  fallback_url="$(download_rootfs_archive || true)"
  if [ -z "${fallback_url}" ]; then
    printf '%s\n' "Unable to prepare a local ${PROOT_DISTRO} rootfs archive for fallback installation." >&2
    return 1
  fi

  printf 'Retrying %s install from local rootfs archive: %s\n' "${PROOT_DISTRO}" "${fallback_url}"
  PD_OVERRIDE_TARBALL_URL="${fallback_url}" PD_OVERRIDE_TARBALL_SHA256="" proot-distro install "${PROOT_DISTRO}"
}

runtime_python_platform() {
  run_in_distro "'${ENV_DIR}/bin/python' -c 'import sysconfig; print(sysconfig.get_platform())'"
}

sync_runtime_scripts() {
  local source_dir="${BACKEND_DIR}/scripts"
  mkdir -p "${SCRIPT_DIR}"
  for script_name in first_boot.sh proot-setup.sh start.sh stop.sh termux_boot.sh update.sh; do
    if [ -f "${source_dir}/${script_name}" ]; then
      cp "${source_dir}/${script_name}" "${SCRIPT_DIR}/${script_name}"
      chmod 755 "${SCRIPT_DIR}/${script_name}"
    fi
  done
}

ensure_runtime_layout() {
  mkdir -p "${INSTALL_ROOT}" "${DATA_DIR}" "${STATE_DIR}" "${LOG_DIR}" "${CACHE_DIR}" "${MODELS_DIR}" "${SCRIPT_DIR}" "${ROOTFS_CACHE_DIR}" "${TOOLS_DIR}"
}

ensure_runtime_tool_layout() {
  run_in_distro "mkdir -p '${TOOLS_DIR}' '${TOOLS_BIN_DIR}'"
}

repair_backend_checkout() {
  if [ ! -e "${BACKEND_DIR}" ]; then
    return
  fi

  if [ -d "${BACKEND_DIR}/.git" ] && git -C "${BACKEND_DIR}" rev-parse --is-inside-work-tree >/dev/null 2>&1 && [ -f "${BACKEND_DIR}/pyproject.toml" ] && [ -f "${BACKEND_DIR}/scripts/proot-setup.sh" ]; then
    return
  fi

  printf '%s\n' 'Repairing broken Mordecai backend checkout in place before continuing...'
  rm -rf "${BACKEND_DIR}"
}

repair_llama_cpp_checkout() {
  ensure_runtime_tool_layout

  if run_in_distro "test -d '${LLAMA_CPP_DIR}/.git' && test -f '${LLAMA_CPP_DIR}/CMakeLists.txt'"; then
    if run_in_distro "git -C '${LLAMA_CPP_DIR}' rev-parse --is-inside-work-tree >/dev/null 2>&1"; then
      return
    fi
  fi

  printf '%s\n' 'Repairing broken llama.cpp tool checkout in place before continuing...'
  run_in_distro "rm -rf '${LLAMA_CPP_DIR}' '${LLAMA_CPP_BUILD_DIR}'"
}

installer_version() {
  awk -F'"' '/^version = "/ { print $2; exit }' "${BACKEND_DIR}/pyproject.toml"
}

installer_commit() {
  if [ -d "${BACKEND_DIR}/.git" ] && git -C "${BACKEND_DIR}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git -C "${BACKEND_DIR}" rev-parse HEAD
    return
  fi
  printf '%s\n' 'unknown'
}

write_install_verification_report() {
  local report_file="$1"
  local backend_log_file="$2"
  local smoke_result="$3"
  local smoke_detail="$4"
  local service_port="$5"
  local status_url="$6"
  local provider_registry_url="$7"
  local tool_manifest_url="$8"
  local voice_engines_url="$9"
  local already_running="${10}"
  local started_here="${11}"
  local local_model_runtimes_enabled="${12}"
  local installer_version_value="${13}"
  local installer_commit_value="${14}"
  local backend_log_tail=""

  mkdir -p "${LOG_DIR}"
  if [ "${smoke_result}" != "passed" ] && [ -f "${backend_log_file}" ]; then
    backend_log_tail="$(tail -n 20 "${backend_log_file}" 2>/dev/null || true)"
  fi

  run_in_distro "REPORT_FILE='${report_file}' BACKEND_LOG_FILE='${backend_log_file}' SMOKE_RESULT='${smoke_result}' SMOKE_DETAIL='${smoke_detail}' SERVICE_PORT='${service_port}' STATUS_URL='${status_url}' PROVIDER_REGISTRY_URL='${provider_registry_url}' TOOL_MANIFEST_URL='${tool_manifest_url}' VOICE_ENGINES_URL='${voice_engines_url}' BACKEND_WAS_RUNNING='${already_running}' BACKEND_STARTED_BY_SMOKE_CHECK='${started_here}' LOCAL_MODEL_RUNTIMES_ENABLED='${local_model_runtimes_enabled}' INSTALLER_VERSION='${installer_version_value}' INSTALLER_COMMIT='${installer_commit_value}' BACKEND_LOG_TAIL='${backend_log_tail}' '${ENV_DIR}/bin/python' -c \"import json, os, pathlib; from datetime import datetime, timezone; report = {'report': 'mordecai-install-verification', 'timestamp_utc': datetime.now(timezone.utc).isoformat(), 'installer_version': os.environ['INSTALLER_VERSION'], 'installer_commit': os.environ['INSTALLER_COMMIT'], 'result': os.environ['SMOKE_RESULT'], 'detail': os.environ['SMOKE_DETAIL'], 'service_port': int(os.environ['SERVICE_PORT']), 'status_url': os.environ['STATUS_URL'], 'provider_registry_url': os.environ['PROVIDER_REGISTRY_URL'], 'tool_manifest_url': os.environ['TOOL_MANIFEST_URL'], 'voice_engines_url': os.environ['VOICE_ENGINES_URL'], 'backend_was_running': os.environ['BACKEND_WAS_RUNNING'] == 'true', 'backend_started_by_smoke_check': os.environ['BACKEND_STARTED_BY_SMOKE_CHECK'] == 'true', 'local_model_runtimes_enabled': os.environ['LOCAL_MODEL_RUNTIMES_ENABLED'], 'backend_log_file': os.environ['BACKEND_LOG_FILE'], 'backend_log_tail': os.environ['BACKEND_LOG_TAIL'].splitlines()}; path = pathlib.Path(os.environ['REPORT_FILE']); path.parent.mkdir(parents=True, exist_ok=True); path.write_text(json.dumps(report, indent=2) + '\\n', encoding='utf-8')\""
}

run_post_install_smoke_check() {
  local service_port="${MORDECAI_SERVICE_PORT:-8000}"
  local status_url="http://127.0.0.1:${service_port}/api/status"
  local provider_registry_url="http://127.0.0.1:${service_port}/api/runtime/provider-registry"
  local tool_manifest_url="http://127.0.0.1:${service_port}/api/runtime/tool-manifest"
  local voice_engines_url="http://127.0.0.1:${service_port}/api/voice/engines"
  local pid_file="${LOG_DIR}/backend.pid"
  local backend_log_file="${LOG_DIR}/backend.log"
  local report_file="${LOG_DIR}/install-verification-report.json"
  local existing_pid=""
  local already_running="false"
  local started_here="false"
  local smoke_result="failed"
  local smoke_detail="Smoke check did not complete."
  local installer_version_value
  local installer_commit_value
  local attempt
  local curl_status

  printf '%s\n' 'Running post-install backend smoke check...'
  installer_version_value="$(installer_version)"
  installer_commit_value="$(installer_commit)"
  trap 'smoke_exit=$?; write_install_verification_report "${report_file}" "${backend_log_file}" "${smoke_result}" "${smoke_detail}" "${service_port}" "${status_url}" "${provider_registry_url}" "${tool_manifest_url}" "${voice_engines_url}" "${already_running}" "${started_here}" "${INSTALL_LOCAL_MODEL_BINARIES}" "${installer_version_value}" "${installer_commit_value}";
if [ "${started_here}" = "true" ] && [ -x "${SCRIPT_DIR}/stop.sh" ]; then "${SCRIPT_DIR}/stop.sh" >/dev/null 2>&1 || true; fi
return ${smoke_exit}' RETURN

  if [ -f "${pid_file}" ]; then
    existing_pid="$(cat "${pid_file}")"
    if [ -n "${existing_pid}" ] && kill -0 "${existing_pid}" 2>/dev/null; then
      already_running="true"
    fi
  fi

  if [ "${already_running}" != "true" ] && "${TERMUX_PREFIX}/bin/curl" --fail --silent --show-error "${status_url}" >/dev/null 2>&1; then
    already_running="true"
  fi

  if [ "${already_running}" = "true" ]; then
    printf '%s\n' 'Backend already running; preserving the existing process for smoke validation.'
  else
    "${SCRIPT_DIR}/start.sh"
    started_here="true"
  fi

  for attempt in 1 2 3 4 5 6 7 8 9 10; do
    if "${TERMUX_PREFIX}/bin/curl" --fail --silent --show-error "${status_url}" >/dev/null; then
      break
    fi
    sleep 2
  done

  if ! "${TERMUX_PREFIX}/bin/curl" --fail --silent --show-error "${status_url}" >/dev/null; then
    curl_status=$?
    smoke_detail="Backend status probe failed at ${status_url} with exit code ${curl_status}."
    return "${curl_status}"
  fi

  if ! run_in_distro "'${ENV_DIR}/bin/python' -c \"import json, urllib.request; provider_registry = json.load(urllib.request.urlopen('${provider_registry_url}')); assert provider_registry['contract'] == 'provider-registry'; assert isinstance(provider_registry['providers'], list) and provider_registry['providers']; tool_manifest = json.load(urllib.request.urlopen('${tool_manifest_url}')); assert tool_manifest['contract'] == 'tool-manifest'; assert isinstance(tool_manifest['tools'], list); assert tool_manifest['tool_count'] == len(tool_manifest['tools']); voice_engines = json.load(urllib.request.urlopen('${voice_engines_url}')); assert 'catalog_summary' in voice_engines; assert 'recommended_stack' in voice_engines; assert 'piper' in voice_engines; assert 'whisper' in voice_engines\""; then
    smoke_detail="Runtime API contract probe failed for provider registry, tool manifest, or voice engines."
    return 1
  fi

  if [ "${INSTALL_LOCAL_MODEL_BINARIES}" = "true" ]; then
    if ! run_in_distro "PATH='${TOOLS_BIN_DIR}:${ENV_DIR}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' /bin/bash -lc 'command -v llama-cli >/dev/null && command -v whisper >/dev/null && command -v piper >/dev/null'"; then
      smoke_detail="Managed local runtime commands were not all visible on PATH inside the runtime."
      return 1
    fi
  fi

  smoke_result="passed"
  smoke_detail="Backend responded to status/provider/tool/voice probes and runtime commands were available as expected."
}

force_reinstall_runtime_layers() {
  if [ "${FORCE_REINSTALL}" != "true" ]; then
    return
  fi

  printf '%s\n' 'Force reinstall requested; removing backend checkout, runtime environment, tools, and copied scripts while preserving models and state...'
  rm -rf "${BACKEND_DIR}" "${ENV_DIR}" "${TOOLS_DIR}" "${SCRIPT_DIR}"
}

verify_runtime_python_install() {
  printf '%s\n' 'Verifying Mordecai Python runtime dependencies...'
  run_in_distro "'${ENV_DIR}/bin/python' -m pip check"
  run_in_distro "'${ENV_DIR}/bin/python' -c \"import fastapi, httpx, yaml, pydantic_settings, uvicorn; import mordecai, mordecai_core, providers, self_mod, net_proxy, voice\""
}

verify_default_model_bundle() {
  if [ "${INSTALL_DEFAULT_MODELS}" != "true" ]; then
    return
  fi

  printf '%s\n' 'Verifying default local model bundle assets...'
  run_in_distro "test -f '${MODELS_DIR}/Qwen2.5-3B-Instruct-Q4_K_M.gguf'"
  run_in_distro "test -f '${MODELS_DIR}/en_US-lessac-medium.onnx'"
  run_in_distro "test -f '${MODELS_DIR}/en_US-lessac-medium.onnx.json'"
}

install_voice_runtime_python_packages() {
  local runtime_platform
  runtime_platform="$(runtime_python_platform)"

  if printf '%s' "${runtime_platform}" | grep -qi '^linux-'; then
    printf '%s\n' 'Preinstalling CPU-only Torch for openai-whisper on the Linux runtime to avoid unsupported CUDA/NVIDIA wheel resolution on Termux/proot installs...'
    run_in_distro "'${ENV_DIR}/bin/python' -m pip install --index-url '${TORCH_CPU_INDEX_URL}' 'torch<3'"
  fi

  run_in_distro "'${ENV_DIR}/bin/python' -m pip install openai-whisper piper-tts"
}

verify_voice_runtime_python_packages() {
  printf '%s\n' 'Verifying local voice runtime Python packages...'
  run_in_distro "'${ENV_DIR}/bin/python' -c \"import torch, whisper, onnxruntime; assert torch.version.cuda is None, torch.version.cuda\""
}

install_local_model_binaries() {
  if [ "${INSTALL_LOCAL_MODEL_BINARIES}" != "true" ]; then
    return
  fi

  printf '%s\n' 'Installing phone-supported local model runtime binaries inside the Linux runtime...'
  ensure_runtime_tool_layout
  run_in_distro 'export DEBIAN_FRONTEND=noninteractive; apt-get update; apt-get install -y ca-certificates curl ffmpeg cmake ninja-build pkg-config python3-dev git build-essential'
  run_in_distro "'${ENV_DIR}/bin/python' -m pip install --upgrade pip setuptools wheel"
  install_voice_runtime_python_packages
  run_in_distro "'${ENV_DIR}/bin/python' -m pip check"
  verify_voice_runtime_python_packages

  repair_llama_cpp_checkout
  run_in_distro "if [ ! -d '${LLAMA_CPP_DIR}/.git' ]; then git clone --depth 1 https://github.com/ggml-org/llama.cpp '${LLAMA_CPP_DIR}'; else git -C '${LLAMA_CPP_DIR}' pull --ff-only; fi"
  run_in_distro "cmake -S '${LLAMA_CPP_DIR}' -B '${LLAMA_CPP_BUILD_DIR}' -DCMAKE_BUILD_TYPE=Release -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_SERVER=OFF -DLLAMA_CURL=OFF"
  run_in_distro "cmake --build '${LLAMA_CPP_BUILD_DIR}' -j\$(nproc)"

  run_in_distro "command -v ffmpeg >/dev/null"
  run_in_distro "command -v cmake >/dev/null"
  run_in_distro "command -v git >/dev/null"
  run_in_distro "test -x '${ENV_DIR}/bin/whisper'"
  run_in_distro "test -x '${ENV_DIR}/bin/piper'"
  run_in_distro "if [ -x '${LLAMA_CPP_BUILD_DIR}/bin/llama-cli' ]; then true; elif [ -x '${LLAMA_CPP_BUILD_DIR}/bin/main' ]; then true; else echo 'llama.cpp CLI binary not found after build' >&2; exit 1; fi"

  run_in_distro "ln -sf '${ENV_DIR}/bin/whisper' '${TOOLS_BIN_DIR}/whisper'"
  run_in_distro "ln -sf '${ENV_DIR}/bin/piper' '${TOOLS_BIN_DIR}/piper'"
  run_in_distro "if [ -x '${LLAMA_CPP_BUILD_DIR}/bin/llama-cli' ]; then ln -sf '${LLAMA_CPP_BUILD_DIR}/bin/llama-cli' '${TOOLS_BIN_DIR}/llama-cli'; else ln -sf '${LLAMA_CPP_BUILD_DIR}/bin/main' '${TOOLS_BIN_DIR}/llama-cli'; fi"

  mkdir -p "${TOOLS_DIR}"
  cat > "${TOOLS_DIR}/local-model-runtime.txt" <<EOF
Installed phone-supported local model runtime binaries

Commands:
- ${TOOLS_BIN_DIR}/llama-cli
- ${TOOLS_BIN_DIR}/whisper
- ${TOOLS_BIN_DIR}/piper

Backed by:
- ${LLAMA_CPP_BUILD_DIR}/bin/llama-cli or ${LLAMA_CPP_BUILD_DIR}/bin/main
- ${ENV_DIR}/bin/whisper
- ${ENV_DIR}/bin/piper
EOF
}

download_shell_apk() {
  printf 'Downloading Mordecai shell APK from %s\n' "${APK_DOWNLOAD_URL}"
  "${TERMUX_PREFIX}/bin/curl" --fail --retry 5 --retry-connrefused --retry-delay 5 --location \
    --output "${APK_DOWNLOAD_PATH}.tmp" "${APK_DOWNLOAD_URL}"
  mv -f "${APK_DOWNLOAD_PATH}.tmp" "${APK_DOWNLOAD_PATH}"
}

installed_shell_package_info() {
  local package_dump
  local version_code
  local version_name

  package_dump="$(dumpsys package "${APK_PACKAGE_NAME}" 2>/dev/null || true)"
  if [ -z "${package_dump}" ]; then
    return 1
  fi

  version_code="$(printf '%s\n' "${package_dump}" | sed -n 's/.*versionCode=\([0-9][0-9]*\).*/\1/p' | head -n 1)"
  version_name="$(printf '%s\n' "${package_dump}" | sed -n 's/.*versionName=\([^[:space:]]*\).*/\1/p' | head -n 1)"

  if [ -z "${version_code}" ] && [ -z "${version_name}" ]; then
    return 1
  fi

  printf '%s|%s\n' "${version_code}" "${version_name}"
}

downloaded_shell_apk_info() {
  local badging
  local version_code
  local version_name

  if ! command -v aapt >/dev/null 2>&1; then
    return 1
  fi

  badging="$(aapt dump badging "${APK_DOWNLOAD_PATH}" 2>/dev/null || true)"
  if [ -z "${badging}" ]; then
    return 1
  fi

  version_code="$(printf '%s\n' "${badging}" | sed -n "s/.*versionCode='\([^']*\)'.*/\1/p" | head -n 1)"
  version_name="$(printf '%s\n' "${badging}" | sed -n "s/.*versionName='\([^']*\)'.*/\1/p" | head -n 1)"

  if [ -z "${version_code}" ] && [ -z "${version_name}" ]; then
    return 1
  fi

  printf '%s|%s\n' "${version_code}" "${version_name}"
}

installed_shell_apk_path() {
  pm path "${APK_PACKAGE_NAME}" 2>/dev/null | sed -n 's/^package://p' | head -n 1
}

apk_sha256() {
  local apk_path="$1"
  if [ ! -r "${apk_path}" ]; then
    return 1
  fi
  sha256sum "${apk_path}" | awk '{ print $1 }'
}

should_install_shell_apk() {
  local installed_info
  local downloaded_info
  local installed_version_code
  local installed_version_name
  local downloaded_version_code
  local downloaded_version_name
  local installed_apk_path
  local installed_hash
  local downloaded_hash

  installed_info="$(installed_shell_package_info || true)"
  if [ -z "${installed_info}" ]; then
    printf '%s\n' 'Mordecai shell package is not currently installed; proceeding with APK install.'
    return 0
  fi

  installed_version_code="${installed_info%%|*}"
  installed_version_name="${installed_info#*|}"
  printf 'Installed Mordecai shell package version: code=%s name=%s\n' "${installed_version_code:-unknown}" "${installed_version_name:-unknown}"

  downloaded_info="$(downloaded_shell_apk_info || true)"
  if [ -n "${downloaded_info}" ]; then
    downloaded_version_code="${downloaded_info%%|*}"
    downloaded_version_name="${downloaded_info#*|}"
    printf 'Downloaded Mordecai shell APK version: code=%s name=%s\n' "${downloaded_version_code:-unknown}" "${downloaded_version_name:-unknown}"

    if [ -n "${downloaded_version_code}" ] && [ -n "${installed_version_code}" ] && [ "${downloaded_version_code}" -gt "${installed_version_code}" ]; then
      printf '%s\n' 'Downloaded shell APK is newer than the installed app; proceeding with update.'
      return 0
    fi

    if [ "${downloaded_version_code}" != "${installed_version_code}" ] || [ "${downloaded_version_name}" != "${installed_version_name}" ]; then
      printf '%s\n' 'Downloaded shell APK version differs from the installed app; proceeding with update.'
      return 0
    fi
  fi

  installed_apk_path="$(installed_shell_apk_path || true)"
  installed_hash="$(apk_sha256 "${installed_apk_path}" 2>/dev/null || true)"
  downloaded_hash="$(apk_sha256 "${APK_DOWNLOAD_PATH}" 2>/dev/null || true)"

  if [ -n "${installed_hash}" ] && [ -n "${downloaded_hash}" ]; then
    if [ "${installed_hash}" = "${downloaded_hash}" ]; then
      printf '%s\n' 'Downloaded shell APK matches the installed app; skipping reinstall.'
      return 1
    fi

    printf '%s\n' 'Downloaded shell APK differs from the installed app payload; proceeding with update.'
    return 0
  fi

  printf '%s\n' 'Unable to prove the downloaded shell APK matches the installed app; proceeding with update to stay safe.'
  return 0
}

install_shell_apk() {
  if [ "${INSTALL_SHELL_APK}" != "true" ]; then
    return
  fi

  download_shell_apk

  if ! should_install_shell_apk; then
    return
  fi

  if command -v su >/dev/null 2>&1 && su -c true >/dev/null 2>&1; then
    if su -c "pm install -r '${APK_DOWNLOAD_PATH}'"; then
      printf '%s\n' 'Installed Mordecai shell APK silently through root package manager access.'
      return
    fi
    printf '%s\n' 'Root package install failed; falling back to the interactive Android package installer.' >&2
  fi

  if command -v termux-open >/dev/null 2>&1; then
    termux-open --content-type application/vnd.android.package-archive "${APK_DOWNLOAD_PATH}"
    printf '%s\n' 'Launched the Android package installer for the Mordecai shell APK. Confirm the install prompt on the device if Android requests it.'
    return
  fi

  printf '%s\n' 'Unable to launch the Android package installer automatically because termux-open is unavailable.' >&2
  return 1
}

install_debug_toolkit() {
  if [ "${INSTALL_DEBUG_TOOLKIT}" != "true" ]; then
    return
  fi

  printf '%s\n' 'Installing optional Mordecai debugging toolkit inside the Linux runtime...'
  run_in_distro 'export DEBIAN_FRONTEND=noninteractive; apt-get update; apt-get install -y procps lsof strace iproute2 net-tools'
  run_in_distro "'${ENV_DIR}/bin/python' -m pip install py-spy viztracer mitmproxy"

  mkdir -p "${TOOLS_DIR}"
  cat > "${TOOLS_DIR}/debug-toolkit.txt" <<EOF
Installed Mordecai debugging toolkit

Python tools:
- py-spy
- viztracer
- mitmproxy

Linux tools:
- procps
- lsof
- strace
- iproute2
- net-tools

Guide:
- ${BACKEND_DIR}/docs/debugging-guide.md
EOF
}

write_env_file() {
  if [ -f "${ENV_FILE}" ]; then
    return
  fi
  cat > "${ENV_FILE}" <<EOF
MORDECAI_INSTALL_ROOT=${INSTALL_ROOT}
MORDECAI_WORKSPACE_DIR=${BACKEND_DIR}
MORDECAI_DATA_DIR=${DATA_DIR}
MORDECAI_STATE_DIR=${STATE_DIR}
MORDECAI_LOG_DIR=${LOG_DIR}
MORDECAI_CACHE_DIR=${CACHE_DIR}
MORDECAI_MODELS_DIR=${MODELS_DIR}
MORDECAI_PROOT_DISTRO=${PROOT_DISTRO}
MORDECAI_INSTALL_DEFAULT_MODELS=${INSTALL_DEFAULT_MODELS}
MORDECAI_INSTALL_LOCAL_MODEL_BINARIES=${INSTALL_LOCAL_MODEL_BINARIES}
MORDECAI_INSTALL_SHELL_APK=${INSTALL_SHELL_APK}
MORDECAI_INSTALL_DEBUG_TOOLKIT=${INSTALL_DEBUG_TOOLKIT}
MORDECAI_APK_RELEASE_TAG=${APK_RELEASE_TAG}
MORDECAI_APK_ASSET_NAME=${APK_ASSET_NAME}
MORDECAI_APK_DOWNLOAD_URL=${APK_DOWNLOAD_URL}
MORDECAI_MODE=mode-a
MORDECAI_SERVICE_HOST=127.0.0.1
MORDECAI_SERVICE_PORT=8000
MORDECAI_ENABLE_ANDROID_CONTROL=false
MORDECAI_ENABLE_ADVANCED_SELF_IMPROVEMENT=false
MORDECAI_ENABLE_DAEMON_MODE=false
MORDECAI_ALLOW_GIT_PUSH=false
EOF
}

printf '%s\n' 'Updating Termux packages and installing Mordecai prerequisites...'
pkg update -y
pkg upgrade -y
pkg install -y git curl proot-distro

force_reinstall_runtime_layers

ensure_runtime_layout

ensure_pinned_distro_plugin
ensure_proot_distro
repair_backend_checkout

if [ -d "${BACKEND_DIR}/.git" ]; then
  printf '%s\n' 'Updating existing Mordecai checkout...'
  git -C "${BACKEND_DIR}" pull --ff-only
else
  printf '%s\n' 'Cloning Mordecai backend...'
  git clone "${REPO_URL}" "${BACKEND_DIR}"
fi

printf '%s\n' 'Preparing Linux runtime inside proot...'
run_in_distro 'export DEBIAN_FRONTEND=noninteractive; apt-get update; apt-get install -y git python3 python3-venv python3-pip build-essential'

if ! run_in_distro "test -x '${ENV_DIR}/bin/python'"; then
  printf '%s\n' 'Creating Python environment inside proot...'
  run_in_distro "python3 -m venv '${ENV_DIR}'"
fi

runtime_platform="$(runtime_python_platform)"
if printf '%s' "${runtime_platform}" | grep -qi 'android'; then
  printf '%s\n' 'Replacing Android-native virtual environment with a proot Linux environment...'
  rm -rf "${ENV_DIR}"
  run_in_distro "python3 -m venv '${ENV_DIR}'"
fi

run_in_distro "'${ENV_DIR}/bin/python' -m pip install --upgrade pip setuptools wheel"
run_in_distro "'${ENV_DIR}/bin/python' -m pip install -e '${BACKEND_DIR}'"
verify_runtime_python_install

if [ "${INSTALL_LOCAL_MODEL_BINARIES}" = "true" ]; then
  install_local_model_binaries
fi

if [ "${INSTALL_DEFAULT_MODELS}" = "true" ]; then
  printf '%s\n' 'Installing the default local model bundle into Mordecai data/models...'
  run_in_distro "'${ENV_DIR}/bin/python' -m mordecai.local_models --install-root '${INSTALL_ROOT}' --install-bundle phone-starter"
  verify_default_model_bundle
fi

if [ "${INSTALL_DEBUG_TOOLKIT}" = "true" ]; then
  install_debug_toolkit
fi

if [ "${INSTALL_SHELL_APK}" = "true" ]; then
  install_shell_apk
fi

write_env_file
sync_runtime_scripts
run_post_install_smoke_check

printf '\n%s\n' 'Mordecai Phase 1 install complete.'
printf 'Install root: %s\n' "${INSTALL_ROOT}"
printf 'Backend: %s\n' "${BACKEND_DIR}"
printf 'Data: %s\n' "${DATA_DIR}"
printf 'Runtime layer: %s (%s)\n' 'proot-distro' "${PROOT_DISTRO}"
printf 'Local model runtimes: %s\n' "${INSTALL_LOCAL_MODEL_BINARIES}"
printf 'Debug toolkit: %s\n' "${INSTALL_DEBUG_TOOLKIT}"
printf 'Start command: %s\n' "${SCRIPT_DIR}/start.sh"
printf 'First boot check: %s\n' "${SCRIPT_DIR}/first_boot.sh"
printf 'Dashboard URL: %s\n' 'http://127.0.0.1:8000'