#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

if [ -z "${TERMUX_VERSION:-}" ] && [ ! -d "/data/data/com.termux/files/usr" ]; then
  printf '%s\n' 'This installer must be run from Termux.' >&2
  exit 1
fi

INSTALL_ROOT="${MORDECAI_INSTALL_ROOT:-$HOME/mordecai}"
BACKEND_DIR="${INSTALL_ROOT}/backend"
ENV_DIR="${INSTALL_ROOT}/env"
DATA_DIR="${INSTALL_ROOT}/data"
STATE_DIR="${DATA_DIR}/state"
LOG_DIR="${DATA_DIR}/logs"
CACHE_DIR="${DATA_DIR}/cache"
MODELS_DIR="${DATA_DIR}/models"
SCRIPT_DIR="${INSTALL_ROOT}/scripts"
ENV_FILE="${INSTALL_ROOT}/.env"
REPO_URL="${MORDECAI_REPO_URL:-https://github.com/smokydastona/Mordecai-AI-Android.git}"
PROOT_DISTRO="${MORDECAI_PROOT_DISTRO:-ubuntu-24.04}"
TERMUX_PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"
TOOLS_DIR="${INSTALL_ROOT}/tools"
ROOTFS_CACHE_DIR="${CACHE_DIR}/rootfs"
UBUNTU_24_04_ALIAS="ubuntu-24.04"
UBUNTU_24_04_RELEASE="${MORDECAI_UBUNTU_24_04_RELEASE:-24.04.2}"
UBUNTU_24_04_BASE_URL="${MORDECAI_UBUNTU_24_04_BASE_URL:-https://cdimage.ubuntu.com/ubuntu-base/releases/${UBUNTU_24_04_RELEASE}/release}"

run_in_distro() {
  local command="$1"
  proot-distro login "${PROOT_DISTRO}" --shared-tmp -- /bin/bash -lc "${command}"
}

proot_plugin_file() {
  local base_path="${TERMUX_PREFIX}/etc/proot-distro/${PROOT_DISTRO}"

  if [ -f "${base_path}.sh" ]; then
    printf '%s\n' "${base_path}.sh"
    return 0
  fi

  if [ -f "${base_path}.override.sh" ]; then
    printf '%s\n' "${base_path}.override.sh"
    return 0
  fi

  return 1
}

ubuntu_base_arch() {
  case "$1" in
    aarch64)
      printf '%s\n' 'arm64'
      ;;
    arm)
      printf '%s\n' 'armhf'
      ;;
    i686)
      printf '%s\n' 'i386'
      ;;
    x86_64)
      printf '%s\n' 'amd64'
      ;;
    *)
      return 1
      ;;
  esac
}

ensure_pinned_distro_plugin() {
  local plugin_path

  if [ "${PROOT_DISTRO}" != "${UBUNTU_24_04_ALIAS}" ]; then
    return
  fi

  plugin_path="${TERMUX_PREFIX}/etc/proot-distro/${UBUNTU_24_04_ALIAS}.override.sh"
  mkdir -p "${TERMUX_PREFIX}/etc/proot-distro"
  cat > "${plugin_path}" <<EOF
# Generated by Mordecai Phase 1 installer.
# This plug-in pins Ubuntu 24.04 LTS instead of following the moving upstream 'ubuntu' alias.
DISTRO_NAME="Ubuntu (24.04 LTS)"
DISTRO_COMMENT="Pinned Ubuntu Base ${UBUNTU_24_04_RELEASE} profile managed by Mordecai."
TARBALL_STRIP_OPT=0

TARBALL_URL['aarch64']="${UBUNTU_24_04_BASE_URL}/ubuntu-base-${UBUNTU_24_04_RELEASE}-base-arm64.tar.gz"
TARBALL_SHA256['aarch64']=""
TARBALL_URL['arm']="${UBUNTU_24_04_BASE_URL}/ubuntu-base-${UBUNTU_24_04_RELEASE}-base-armhf.tar.gz"
TARBALL_SHA256['arm']=""
TARBALL_URL['i686']="${UBUNTU_24_04_BASE_URL}/ubuntu-base-${UBUNTU_24_04_RELEASE}-base-i386.tar.gz"
TARBALL_SHA256['i686']=""
TARBALL_URL['x86_64']="${UBUNTU_24_04_BASE_URL}/ubuntu-base-${UBUNTU_24_04_RELEASE}-base-amd64.tar.gz"
TARBALL_SHA256['x86_64']=""
EOF
}

termux_arch() {
  case "$(uname -m)" in
    aarch64|arm64)
      printf '%s\n' 'aarch64'
      ;;
    arm|armv7l|armv8l)
      printf '%s\n' 'arm'
      ;;
    i686|i386|x86)
      printf '%s\n' 'i686'
      ;;
    x86_64|amd64)
      printf '%s\n' 'x86_64'
      ;;
    riscv64)
      printf '%s\n' 'riscv64'
      ;;
    *)
      return 1
      ;;
  esac
}

plugin_tarball_field() {
  local plugin_file
  local distro_arch="$1"
  local field_name="$2"

  plugin_file="$(proot_plugin_file || true)"
  if [ -z "${plugin_file}" ]; then
    return 1
  fi

  awk -F'"' -v arch="${distro_arch}" -v field_name="${field_name}" '$0 ~ (field_name "\\[\\x27" arch "\\x27\\]=") { print $2; exit }' "${plugin_file}"
}

download_rootfs_archive() {
  local distro_arch
  local source_url
  local expected_sha256
  local tarball_name
  local archive_path
  local actual_sha256

  distro_arch="$(termux_arch)" || return 1
  source_url="$(plugin_tarball_field "${distro_arch}" 'TARBALL_URL')"
  expected_sha256="$(plugin_tarball_field "${distro_arch}" 'TARBALL_SHA256')"

  if [ -z "${source_url}" ]; then
    printf '%s\n' "Unable to read the ${PROOT_DISTRO} rootfs URL from ${TERMUX_PREFIX}/etc/proot-distro/${PROOT_DISTRO}.sh." >&2
    return 1
  fi

  tarball_name="${source_url##*/}"
  archive_path="${ROOTFS_CACHE_DIR}/${tarball_name}"
  mkdir -p "${ROOTFS_CACHE_DIR}"

  if [ ! -f "${archive_path}" ]; then
    printf 'Downloading %s rootfs archive with curl --http1.1...\n' "${PROOT_DISTRO}"
    "${TERMUX_PREFIX}/bin/curl" --http1.1 --fail --retry 5 --retry-connrefused --retry-delay 5 --location \
      --output "${archive_path}.tmp" "${source_url}"
    mv -f "${archive_path}.tmp" "${archive_path}"
  fi

  if [ -n "${expected_sha256}" ]; then
    actual_sha256="$(sha256sum "${archive_path}" | awk '{ print $1 }')"
    if [ "${actual_sha256}" != "${expected_sha256}" ]; then
      rm -f "${archive_path}"
      printf '%s\n' "Downloaded ${PROOT_DISTRO} rootfs checksum did not match the plugin SHA-256; removed the cached archive." >&2
      return 1
    fi
  fi

  printf 'file://%s\n' "${archive_path}"
}

ensure_proot_distro() {
  local fallback_url

  if proot-distro login "${PROOT_DISTRO}" --shared-tmp -- /usr/bin/env true >/dev/null 2>&1; then
    return
  fi

  printf 'Installing proot distro: %s\n' "${PROOT_DISTRO}"
  if proot-distro install "${PROOT_DISTRO}"; then
    return
  fi

  fallback_url="$(download_rootfs_archive || true)"
  if [ -z "${fallback_url}" ]; then
    printf '%s\n' "Unable to prepare a local ${PROOT_DISTRO} rootfs archive for fallback installation." >&2
    return 1
  fi

  printf 'Retrying %s install from local rootfs archive: %s\n' "${PROOT_DISTRO}" "${fallback_url}"
  PD_OVERRIDE_TARBALL_URL="${fallback_url}" PD_OVERRIDE_TARBALL_SHA256="" proot-distro install "${PROOT_DISTRO}"
}

runtime_python_platform() {
  run_in_distro "'${ENV_DIR}/bin/python' -c 'import sysconfig; print(sysconfig.get_platform())'"
}

sync_runtime_scripts() {
  local source_dir="${BACKEND_DIR}/scripts"
  mkdir -p "${SCRIPT_DIR}"
  for script_name in proot-setup.sh start.sh stop.sh termux_boot.sh update.sh; do
    if [ -f "${source_dir}/${script_name}" ]; then
      cp "${source_dir}/${script_name}" "${SCRIPT_DIR}/${script_name}"
      chmod 755 "${SCRIPT_DIR}/${script_name}"
    fi
  done
}

write_env_file() {
  if [ -f "${ENV_FILE}" ]; then
    return
  fi
  cat > "${ENV_FILE}" <<EOF
MORDECAI_INSTALL_ROOT=${INSTALL_ROOT}
MORDECAI_WORKSPACE_DIR=${BACKEND_DIR}
MORDECAI_DATA_DIR=${DATA_DIR}
MORDECAI_STATE_DIR=${STATE_DIR}
MORDECAI_LOG_DIR=${LOG_DIR}
MORDECAI_CACHE_DIR=${CACHE_DIR}
MORDECAI_MODELS_DIR=${MODELS_DIR}
MORDECAI_PROOT_DISTRO=${PROOT_DISTRO}
MORDECAI_MODE=mode-a
MORDECAI_SERVICE_HOST=127.0.0.1
MORDECAI_SERVICE_PORT=8000
MORDECAI_ENABLE_ANDROID_CONTROL=false
MORDECAI_ENABLE_ADVANCED_SELF_IMPROVEMENT=false
MORDECAI_ENABLE_DAEMON_MODE=false
MORDECAI_ALLOW_GIT_PUSH=false
EOF
}

printf '%s\n' 'Updating Termux packages and installing Mordecai prerequisites...'
pkg update -y
pkg upgrade -y
pkg install -y git curl proot-distro

mkdir -p "${INSTALL_ROOT}" "${DATA_DIR}" "${STATE_DIR}" "${LOG_DIR}" "${CACHE_DIR}" "${MODELS_DIR}" "${SCRIPT_DIR}" "${ROOTFS_CACHE_DIR}"

ensure_pinned_distro_plugin
ensure_proot_distro

if [ -d "${BACKEND_DIR}/.git" ]; then
  printf '%s\n' 'Updating existing Mordecai checkout...'
  git -C "${BACKEND_DIR}" pull --ff-only
elif [ -e "${BACKEND_DIR}" ]; then
  printf '%s\n' "${BACKEND_DIR} exists but is not a git checkout. Move it aside and rerun the installer." >&2
  exit 1
else
  printf '%s\n' 'Cloning Mordecai backend...'
  git clone "${REPO_URL}" "${BACKEND_DIR}"
fi

printf '%s\n' 'Preparing Linux runtime inside proot...'
run_in_distro 'export DEBIAN_FRONTEND=noninteractive; apt-get update; apt-get install -y git python3 python3-venv python3-pip build-essential'

if ! run_in_distro "test -x '${ENV_DIR}/bin/python'"; then
  printf '%s\n' 'Creating Python environment inside proot...'
  run_in_distro "python3 -m venv '${ENV_DIR}'"
fi

runtime_platform="$(runtime_python_platform)"
if printf '%s' "${runtime_platform}" | grep -qi 'android'; then
  printf '%s\n' 'Replacing Android-native virtual environment with a proot Linux environment...'
  rm -rf "${ENV_DIR}"
  run_in_distro "python3 -m venv '${ENV_DIR}'"
fi

run_in_distro "'${ENV_DIR}/bin/python' -m pip install --upgrade pip setuptools wheel"
run_in_distro "'${ENV_DIR}/bin/python' -m pip install -e '${BACKEND_DIR}'"

write_env_file
sync_runtime_scripts

printf '\n%s\n' 'Mordecai Phase 1 install complete.'
printf 'Install root: %s\n' "${INSTALL_ROOT}"
printf 'Backend: %s\n' "${BACKEND_DIR}"
printf 'Data: %s\n' "${DATA_DIR}"
printf 'Runtime layer: %s (%s)\n' 'proot-distro' "${PROOT_DISTRO}"
printf 'Start command: %s\n' "${SCRIPT_DIR}/start.sh"
printf 'Dashboard URL: %s\n' 'http://127.0.0.1:8000'